version: 2.0

jobs:
  build:
    working_directory: ~/dynamic-rest
    parallelism: 1

    docker:
      - image: circleci/python:2.7.15-jessie
    steps:
      - checkout
      - run:
          name: Update PATH variable
          command: echo 'export PATH="${HOME}/.local/bin:${PATH}"' >> ${BASH_ENV}
      - run:
          name: Install python3-devel
          command: sudo apt-get install python3-dev
      - run:
          name: Install from requirements.txt
          command: pip install --user --exists-action w -r requirements.txt
      - run:
          name: Run Setup
          command: python setup.py develop --user
      - run:
          name: Install pyenv
          command: |
            curl -L https://raw.githubusercontent.com/pyenv/pyenv-installer/master/bin/pyenv-installer | bash
            sudo ln -s $HOME/.pyenv/bin/pyenv /usr/local/bin/pyenv && eval "$(pyenv init -)"
            eval "$(pyenv virtualenv-init -)"
      - restore_cache:
          name: Restore PyEnv Cache
          keys:
              - v1-pyenv-cache-{{ checksum ".circleci/python-versions.txt" }}
      - run:
          name: Install python versions for testing
          command: |
            echo "PyEnv Versions already installed:"
            pyenv versions
            pyver="~/.pyenv/versions"
            echo "DEBUG::$pyver: $(ls $pyver)"
            echo "$HOME"
            echo "ls -a $HOME:"
            ls -a "$HOME"
            echo "ls -a $HOME/.pyenv:"
            ls -a "$HOME/.pyenv"
            echo "ls -a ~:"
            ls -a ~
            echo "ls -a ~/.pyenv:"
            ls -a ~/.pyenv
            echo "ls ~/.pyenv/versions"
            ls  ~/.pyenv/versions
            echo "ls $HOME/.pyenv/versions"
            ls  "$HOME/.pyenv/versions"
            echo "ls -a $HOME/dynamic-rest/.pyenv"
            ls -a "$HOME/dynamic-rest/.pyenv"
            python_versions=$(cat .circleci/python-versions.txt)
            echo "Python versions to install: $python_versions"
            for python_version in $python_versions; do
                echo "INSTALLING: Python $python_version"
                pyenv install -s $python_version
            done
            pyenv local  $python_versions
            echo "DEBUG::$pyver: $(ls $pyver)"
      - save_cache:
          name: Save PyEnv Cache
          key: v1-pyenv-cache-{{ checksum ".circleci/python-versions.txt"}}
          paths:
              - "~/.pyenv"

      - run:
          name: Run Integration tests
          command: ENABLE_INTEGRATION_TESTS=True py.test tests/integration
      - run:
          name: Run Tox Tests
          command: tox

workflows:
  version: 2
  build-and-test:
    jobs:
      - build:
          context: org-global
